# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a2ea8c4f9f2fbe9681e17b596f7c83d899eac6ee4ab2b6121bb92447d961578c04b15911bb0623445b2920cb21f06c9e35da3483e9c1a4cb85e9c3d60ef4b48

test:
  secret_key_base: a0e9f4f343f56cb51363fe0b4ab777311098f87b8b13a39c37e519a94ee33269b9871f4604507fab993ef784dd8c991f3c29f22763ddb3561da10f9405f743e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
